# Your taz id (gets read from .env file)
id: ${TAZ_ID}

# Your taz password (gets read from .env file)
password: ${TAZ_PASSWORD}

# In which format do you want to download your newspaper?
# Valid formats are: pdf, epub, epubt, html, ascii, mobi, mobit
download_format: "pdf"

# Where should the downloaded files be stored?
download_folder: "/path/to/download/folder"

# Before the program searches for new download candidates, it checks whether tomorrow's newspaper has already been
# downloaded by the number of queries on the taz.de website.
# If you want to download all available newspaper missing in the download_history.csv, set this value to False.
limit_requests: True

# Set the log level.
# Valid formats are: notset, debug, info, warning, error, critical
log_level: "info"
